spring.application.name=gateway-service
server.port=8080
#
spring.cloud.gateway.routes[0].id=employee-service
spring.cloud.gateway.routes[0].uri=http://localhost:9002
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/employees/**
spring.main.web-application-type=reactive
#
eureka.instance.hostname=localhost
eureka.client.service-url.defautZone=http://localhost:8761/eureka
eureka.client.service-url.register-with-eureka=true
eureka.client.service-url.fetch-registry=true